import {createHash} from 'node:crypto';import {readFile,writeFile,rename,mkdir} from 'node:fs/promises';import {questionSchema,type EditorialRecord} from '../src/lib/schema';
export interface Candidate{sourceId:string;text:string;answer:string;explanation?:string;hints?:[string,string];rightsStatus:'allowed'|'unknown'|'denied';rightsBasis?:string}
export interface SourceAdapter{fetchBatch(checkpoint:string|null,limit:number):Promise<{items:Candidate[];checkpoint:string|null}>}
export class JsonAdapter implements SourceAdapter{constructor(private path:string){}async fetchBatch(checkpoint:string|null,limit:number){const all=JSON.parse(await readFile(this.path,'utf8')) as Candidate[];const from=Number(checkpoint||0);return{items:all.slice(from,from+limit),checkpoint:String(Math.min(all.length,from+limit))}}}
export const normalize=(s:string)=>s.normalize('NFC').replace(/\r\n/g,'\n').replace(/[ \t]+/g,' ').trim();
export const hash=(s:string)=>createHash('sha256').update(normalize(s).toLocaleLowerCase('ru')).digest('hex');
export function inspect(c:Candidate,known=new Set<string>()){const reasons:string[]=[];if(!c.answer?.trim())reasons.push('missing_answer');if(c.rightsStatus!=='allowed'||!c.rightsBasis)reasons.push('rights_not_confirmed');if(/изображ|картин|аудио|видео|раздат|предыдущ/i.test(c.text))reasons.push('media_or_context_dependency');if(known.has(hash(c.text)))reasons.push('duplicate');if(!/[а-яё]/i.test(c.text))reasons.push('language');if(c.hints?.some(h=>normalize(h).toLowerCase().includes(normalize(c.answer).toLowerCase())))reasons.push('hint_leaks_answer');return reasons}
export async function atomicJson(path:string,value:unknown){await mkdir(path.substring(0,path.lastIndexOf('/')),{recursive:true});const tmp=path+'.tmp';await writeFile(tmp,JSON.stringify(value,null,2));await rename(tmp,path)}
export function publicProjection(r:EditorialRecord,production=false){if(r.status!=='published')throw Error('Only published records are public');if(production&&r.isDemo)throw Error('Demo content forbidden in production');return questionSchema.parse({id:r.id,revision:r.revision,publishDate:r.publishDate,text:r.text,answer:r.answer,explanation:r.explanation,hints:r.hints,attribution:r.attribution,isDemo:r.isDemo})}
export class Budget{spent=0;reserved=0;constructor(readonly cap:number){}reserve(max:number){if(this.spent+this.reserved+max>this.cap)return false;this.reserved+=max;return true}settle(reserved:number,actual:number){this.reserved-=reserved;this.spent+=actual}}
